@version: 4.2
@module kafka

source s_mikrotik {
    network(
        ip("0.0.0.0")
        port(514)
        transport("udp")
    );
};

destination d_kafka {
    kafka_c(
        bootstrap-servers("kafka:9092")
        topic("ipdr-events")
    );
};

log {
    source(s_mikrotik);
    destination(d_kafka);
};
